#!/usr/bin/env bash
set -Eeuo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/deebot-x1-local}"
BUMPER="${BUMPER_DIR:-$INSTALL_DIR/vendor/bumper}"
SRC="$BUMPER/docker-compose.yaml"
DST="$BUMPER/docker-compose.x1.yaml"

[[ -f "$SRC" ]] || { echo "Bumper compose not found: $SRC" >&2; exit 2; }

python3 - "$SRC" "$DST" <<'PY'
from pathlib import Path
import sys

src = Path(sys.argv[1])
dst = Path(sys.argv[2])
text = src.read_text()

# DEEBOT X1 uses MQTT/TLS. For the local X1 + Home Assistant stack we only
# publish host ports 443 (Ecovacs HTTPS/MQTT SNI), 8007 (REST), and 8883
# (direct MQTTS for Home Assistant). The following upstream publications are
# useful for legacy/general Bumper deployments but are not required here.
blocks = {
    "nginx HTTP/80": """      # HTTP Server (non TLS)\n      - target: ${WEB_SERVER_LISTEN_PORT:-8007}\n        published: 80\n        protocol: tcp\n        mode: host\n""",
    "plain MQTT/1883": """      # MQTT Server (non TLS)\n      - target: ${MQTT_LISTEN_PORT:-1883}\n        published: ${MQTT_LISTEN_PORT:-1883}\n        protocol: tcp\n        mode: host\n""",
    "XMPP/5223": """      # XMPP Server\n      - target: ${XMPP_LISTEN_PORT_TLS:-5223}\n        published: ${XMPP_LISTEN_PORT_TLS:-5223}\n        protocol: tcp\n        mode: host\n""",
}

for name, block in blocks.items():
    count = text.count(block)
    if count != 1:
        raise SystemExit(
            f"Refusing to generate X1 compose: expected exactly one {name} block, found {count}. "
            "The upstream Bumper compose layout changed; review it before updating."
        )
    text = text.replace(block, "", 1)

banner = "# Generated by DEEBOT X1 Local. Do not edit; regenerate via scripts/prepare-bumper-compose.sh.\n"
dst.write_text(banner + text)
PY

printf 'Prepared %s\n' "$DST"
